[package] [kernel-osmc] Rework root filesystem detection to work with UUID. Drop to busybox shell if root device is not found instead of an infinite sleep.

diff --git a/package/kernel-osmc/initramfs-src/init b/package/kernel-osmc/initramfs-src/init
--- a/package/kernel-osmc/initramfs-src/init
+++ b/package/kernel-osmc/initramfs-src/init
@@ -5,10 +5,11 @@
 
 # Abstract settings and defaults
 
-install_busybox_symlinks()
+busybox_shell()
 {
         # Installs BusyBox symlinks to make the shell actually usable
 	/bin/busybox --install -s
+	/bin/busybox setsid /bin/busybox sh -c 'exec /bin/busybox sh </dev/tty1 >/dev/tty1 2>&1'
 }
 
 OPTION_DO_FSCK="1"
@@ -51,7 +52,7 @@ for option in $(/bin/busybox cat /proc/cmdline); do
 	    OPTION_ROOTDELAY="${option#*=}"
 	    ;;
 	  root=*)
-		OPTION_ROOT="${option#*=}"
+		OPTION_ROOT=$(echo "${option#*=}" | /bin/busybox sed 's/"//g')
 		;;
 	  rootfstype=*)
 		OPTION_FILESYSTEM="${option#*=}"
@@ -72,8 +73,7 @@ for option in $(/bin/busybox cat /proc/cmdline); do
 		OPTION_DO_FSCK="0"
 		;;
 	  osmcrescue)
-		install_busybox_symlinks
-		/bin/busybox sh
+		busybox_shell
 		;;
 	 esac
 done
@@ -92,17 +92,22 @@ fi
 
 # Wait for the root device node to appear if it has still not been added by mdev yet.
 
-COUNTER=0
-while [ ! -b "$OPTION_ROOT" -a "$OPTION_FILESYSTEM" != "nfs" ]; do
-	if [ "$COUNTER" -eq 0 ]; then echo "Waiting for root filesystem device node $OPTION_ROOT..."; fi
-	/bin/busybox sleep 1
-	COUNTER=$((COUNTER+1))
-	if [ "$COUNTER" -ge 30 ]
-	then
-		echo -e "FATAL ERROR: Could not find root filesystem device node - if this is a USB install please check the USB drive is connected.\n\n\n\n"
-		while true; do /bin/busybox sleep 1000; done
-	fi
-done
+if [ "$OPTION_FILESYSTEM" != "nfs" ]
+then
+	COUNTER=0
+	echo "Waiting for root filesystem device $OPTION_ROOT"
+	while ! /bin/busybox blkid | /bin/busybox sed 's/"//g' | /bin/busybox grep -q "$OPTION_ROOT"; do
+        /bin/busybox sleep 1
+        COUNTER=$((COUNTER+1))
+        if [ "$COUNTER" -ge 30 ]
+        then
+                echo "FATAL ERROR: Could not find root filesystem device $OPTION_ROOT - if this is a USB install please check the USB drive is connected."
+		# Drop to a shell
+		busybox_shell
+		break
+        fi
+	done
+fi
 
 # Should we check the filesystem?
 
@@ -197,6 +202,5 @@ then
 else
 	echo "OSMC cannot mount $OPTION_ROOT of $OPTION_FILESYSTEM filesystem"
 	# Drop to a shell
-	install_busybox_symlinks
-	/bin/busybox sh
+	busybox_shell
 fi
