[package] [base-files-osmc] manual-update service rewrite. After updating check if we can remove unneeded kernels. The currently booted kernel and the one depended on by *-kernel-osmc will not be removed. Update dialog error messages.

diff --git a/package/base-files-osmc/files/usr/bin/manual-update b/package/base-files-osmc/files/usr/bin/manual-update
--- a/package/base-files-osmc/files/usr/bin/manual-update
+++ b/package/base-files-osmc/files/usr/bin/manual-update
@@ -45,19 +45,29 @@ then
 	package="${pkgarr[0]}"; if [ -n "${pkgarr[1]}" ]; then package="$package (${pkgarr[1]})"; fi
 	if [ -z "$package" ]; then package="(unknown package)"; fi
 
-	dialog --backtitle "Package configuration" --title "OSMC Update Error" --infobox "\n    An error occurred while installing the following package:\n    $package\n\n    Please report this problem on the OSMC forum. Attempting\n    to restart Kodi in 30 seconds...\n" 9 71 > /dev/tty1
+	dialog --backtitle "Package configuration" --title "OSMC Update Error" --infobox "\n    An error occurred while installing the following package:\n    $package\n\n    Please report this problem on the OSMC forum, making sure to\n    include debug logs. Attempting to restart Kodi in 30 seconds...\n" 9 74 > /dev/tty1
 	echo $package > $failed; chown osmc:osmc $failed
-	sleep 30
+	sleep 25
 else
 	rm -f $suppress
-	. /etc/osmc/prefs.d/*
-	removable_kernels=$(dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d')
-	if [ ! -z "$removable_kernels" ] && [[ ! -z "$OSMC_KERNEL_AUTOREMOVE"  || "$OSMC_KERNEL_AUTOREMOVE" == "1" ]]
+	[ -e /etc/osmc/prefs.d/update_preferences ] && . /etc/osmc/prefs.d/update_preferences
+
+	desired_kernel=$(dpkg-query -W -f='${Depends}\n' "*-kernel-osmc" | sed -e 's/, */,/g' -e 's/\,/\n/g' | egrep -o ".*-image-.*-osmc")
+	running_kernel="-image-$(uname -r)"
+	removable_kernels=$(dpkg-query -W -f='${Package}\n' "*-image-*-osmc" | grep -v "$desired_kernel\|$running_kernel")
+
+	if [ -n "$removable_kernels" ] && [ "$OSMC_KERNEL_AUTOREMOVE" = "1" ]
 	then
-	    debconf-apt-progress --logfile $tmp -- apt-get -y purge $removable_kernels > /dev/tty1
+		if ! debconf-apt-progress --logfile $tmp -- apt-get -y purge $removable_kernels > /dev/tty1
+		then
+			dialog --backtitle "Package configuration" --title "OSMC Update Error" --infobox "\n    An error occurred removing no longer required kernel packages.\n\n    Please report this problem on the OSMC forum, making sure to\n    include debug logs. Attempting to restart Kodi in 30 seconds...\n" 9 74 > /dev/tty1
+			echo -e "\nError removing old kernels during manual-update:" >> /var/log/apt/term.log
+			cat $tmp >> /var/log/apt/term.log
+			sleep 25
+		fi
 	fi
-	sleep 5
 fi
+sleep 5
 
 rm -f $tmp
 if [ -f /tmp/reboot-needed ] || [ -f /var/run/reboot-required ]; then reboot; exit; fi
