[package] [base-files-osmc] Add error dialogue to manual update service to report package that failed to install.

diff --git a/package/base-files-osmc/files/usr/bin/manual-update b/package/base-files-osmc/files/usr/bin/manual-update
--- a/package/base-files-osmc/files/usr/bin/manual-update
+++ b/package/base-files-osmc/files/usr/bin/manual-update
@@ -4,7 +4,8 @@
 # email@samnazarko.co.uk
 
 export TERM=linux
-#export DEBCONF_NOWARNINGS=yes
+export LANG=C
+
 systemctl stop getty@tty1
 clear > /dev/tty1
 chvt 1
@@ -12,10 +13,17 @@ systemctl stop mediacenter
 
 # Package downloads have been done in the addon, so let's get right to upgrade.
 
-debconf-apt-progress -- apt-get -y dist-upgrade > /dev/tty1
-rm -f /var/tmp/.suppress_osmc_update_checks
-sleep 5
+tmp=$(tempfile)
+if ! debconf-apt-progress --logfile $tmp -- apt-get -y dist-upgrade > /dev/tty1; then
+	package=$(grep -A 1 "Errors were encountered while processing" $tmp | tail -n 1 | sed 's/.*\///' | awk -F"_" '{print $1" ("$2")"}')
+	dialog --title " OSMC Update Error " --infobox "\n    An error occurred while installing the following package:\n    $package\n\n    Please report this problem in the OSMC forum. Attempting\n    to restart Kodi in 30 seconds.\n" 9 71 > /dev/tty1
+	sleep 30
+else
+	rm -f /var/tmp/.suppress_osmc_update_checks
+	sleep 5
+fi
 
+rm -f $tmp
 if [ -f /tmp/reboot-needed ] || [ -f /var/run/reboot-required ]; then reboot; exit; fi
 clear > /dev/tty1
 systemctl start mediacenter
