[package] [base-files-osmc] Fix error reporting for paste-log when the log file is too big for the server and small code refactor.

diff --git a/package/base-files-osmc/files/usr/bin/paste-log b/package/base-files-osmc/files/usr/bin/paste-log
--- a/package/base-files-osmc/files/usr/bin/paste-log
+++ b/package/base-files-osmc/files/usr/bin/paste-log
@@ -1,17 +1,24 @@
 #!/bin/bash
 
 if [ $# -ne 0 ]; then
-	response=$(curl -X POST -s -T "$1" https://paste.osmc.tv/documents) || response=$(curl -X POST -s -0 -T "$1" https://paste.osmc.tv/documents)
+	file=$1
 else
-	tmp=$(mktemp)
-	trap "rm -f $tmp" EXIT
-	cat >| $tmp
-
-	response=$(curl -X POST -s -T "$tmp" https://paste.osmc.tv/documents) || response=$(curl -X POST -s -0 -T "$tmp" https://paste.osmc.tv/documents)
+	file=$(mktemp)
+	trap "rm -f $file" EXIT
+	cat >| $file
 fi
+	response=$(curl -X POST -s -T "$file" https://paste.osmc.tv/documents) || response=$(curl -X POST -s -0 -T "$file" https://paste.osmc.tv/documents)
 
 if [ "$?" -eq 0 ]; then
-	echo "$response" | awk -F '"' '{print "https://paste.osmc.tv/"$4}'
+	case "$response" in
+		*"413 Request Entity Too Large"*)
+			size=$(du -h "$file" | cut -f1)
+			echo "Unable to upload log. Log file is too large. (${size}B)"
+			;;
+		*)
+			echo "$response" | awk -F '"' '{print "https://paste.osmc.tv/"$4}'
+			;;
+	esac
 else
 	echo "Unable to upload log. Please check your internet connection."
 fi
